### PR TITLE
Support QDA format

### PR DESCRIPTION
**Pull request by eterX**
PR #505, reborn. *now* "Able to merge".  One-file import/export format, as discussed in #507

Doorstop <-> REFI-QDA mapping is documented and implemented in qdatools and _one_file_qdc(), both in importer.py and in exporter.py.

importer.qdatools and exporter.qdatools contain settings and support the low-level logic of data presentation. The high-level logic, say applicacion logic, is implemented in importer._onefile_qdc() and exporter._onefile_qdc(). importer.py acts as master.

REFI-QDA support module only handles QDC files so far. Therefore doorstop.Tree, doorstop.Document and doorstop.Item are the sole entities represented in the exchange. In future releases, external reference blobs will be embedded in QDPX files (not yet supported by the module portableQDA)

By the moment, unsupported attributes are: 'level', 'references', 'derived', 'active', 'ref', 'links', 'normative', 'reviewed'. They are silently ignored, and set to default in a export/import round-trip operation.

All tests at test_all.py pass.

### CODE REVIEW

**Comment by neerdoc** [comment]
Hi @eterX, we have recently improved the CI-functionality a lot, so it would be great if you could merge the latest from the develop-branch into your PR.

**Comment by eterX** [comment]
Hi @neerdoc ,

will try ASAP. Thanks

**Comment by neerdoc** [comment]
@eterX Just a friendly reminder/question. Do you intend to update this PR?

**Comment by eterX** [comment]
> @eterX Just a friendly reminder/question. Do you intend to update this PR?

Hi Gustav,

It turned out that this format was not as popular/useful as I though. That is judging by the lack of contributions to the [underlying library](https://gitlab.com/portableqda/portableQDA), which I kept as alpha all this time.

So, sadly, no: I don't think that this feature would be worth contributing farther to.

Thank you for asking!!  (and for Doorstop ingeneral) :)

**Comment by neerdoc** [comment]
Thank you for getting back to us @etherX, I'll just close this PR then.

**Pull request closed without merging**
