### PR TITLE
Custom item validator per folder

### PR DESCRIPTION
**Pull request by lbiaggi**
Hi @jacebrowning, we have been using doorstop to manage our ISO 26262 requirements, it is part of our core workflow.

We have improved certain areas of the software to match our requirements, and we think it would be useful to share with upstream these changes.

- Load a file as a python module
- A new section inside `.doorstop.yml`  to enable them (we called them extension, as we intend to add more features if necessary) 
       -  Where we can define a custom validator for the items from a specific folder
       -  If file references from this folder should calculate the SHA-256 for them (During review / validate without `-W`)
            -  Change the buffer size for when doing the SHA
- Override doorstop settings from a file through CLI parameter.
 
We made these changes because we didn't want to override most of the default behaviour from doorstop, and yet we wanted to be able to tweak certain validations for specific items.

### CODE REVIEW

**Comment by neerdoc** [comment]
@lbiaggi I've had a quick look and it looks very useful! I will do a deeper review and some testing as soon as possible.

**Review by neerdoc — CHANGES_REQUESTED** [review]
The changes looks good as far as I can see, and would possibly fix #564.

The only issue I have is that there are no tests included for the added functionality.

Please add relevant test cases for the added functionality.

**Comment by lbiaggi** [comment]
> The changes looks good as far as I can see, and would possibly fix #564.
> 
> The only issue I have is that there are no tests included for the added functionality.
> 
> Please add relevant test cases for the added functionality.

Ok!

**Comment by lbiaggi** [comment]
Can you re-review @neerdoc? I've inserted tests, updated the sample reqs project and documentation.

**Review by neerdoc — COMMENTED** [review]
I've had another look and as far as I can see this is a nice improvement. 

It is a rather big change (lot's of new code, I like it!) so I would like to test it a bit more on my own system before we merge it, but good work @lbiaggi!

@jacebrowning should also have a look at it.

**Review by neerdoc — APPROVED** [review]

**Comment by lbiaggi** [comment]
@neerdoc no worries, I understand.

How can I propose more drastic changes? (I'm looking to improve and expand references type to be more generic and customizable, e.g., to support external links  from another repo.) or at least an interface to create custom references.

**Comment by lbiaggi** [comment]
Should I rebase and fix the conflict?

**Comment by neerdoc** [comment]
Yes please, that would be very helpful!

**Comment by lbiaggi** [comment]
Done, if a conflict appears, and I did not update the PR, please ping me

**Comment by lbiaggi** [comment]
Friendly ping reminder

**Comment by lbiaggi** [comment]
Friendly ping reminder @jacebrowning

**Comment by jacebrowning** [comment]
@lbiaggi sorry, I haven't had a chance to look at this until now.

I think we should stick to one feature per merge request (and corresponding issue for discussion, if applicable). Since there are three distinct features here, I'd like to see this split up into three separate merge requests that can be reviewed and applied independently.

**Comment by lbiaggi** [comment]
OK, but bear in mind that I rely on the first one to do the other two

Can I signalize they are dependent? (at least from the first)

**Comment by jacebrowning** [comment]
Yeah, you can identify that they are dependent or just open the base pull request first.

**Comment by lbiaggi** [comment]
@jacebrowning done

**Comment by lbiaggi** [comment]
@jacebrowning ping

**Comment by jacebrowning** [comment]
@lbiaggi this pull request still seems to contain multiple features: custom item validation and something about changing the SHA that I don't fully understand. I'd like to see this split into two separate pull requests for further review. Thanks!

**Comment by lbiaggi** [comment]
> @lbiaggi this pull request still seems to contain multiple features: custom item validation and something about changing the SHA that I don't fully understand. I'd like to see this split into two separate pull requests for further review. Thanks!

Sorry, IMO they were the same feature because without the SHA, custom validator doesn't seem to be doing something interesting.

I'm not changing the SHA, I'm just calculating the SHA for each file reference...

I will do it now.

**Comment by lbiaggi** [comment]
@jacebrowning done, sorry for misinterpreting what you meant

**Pull request merged**
